some clean-up

diff --git a/usb/initrd/wheezy-netboot/usr/lib/debian-installer/retriever/net-retriever b/usb/initrd/wheezy-netboot/usr/lib/debian-installer/retriever/net-retriever
--- a/usb/initrd/wheezy-netboot/usr/lib/debian-installer/retriever/net-retriever
+++ b/usb/initrd/wheezy-netboot/usr/lib/debian-installer/retriever/net-retriever
@@ -23,57 +23,29 @@ fetch() {
 	fetch-url -c "${protocol}://${hostname}${directory}/$1" "$2"
 }
 
-# Note: callers are expected to check for non-empty strings in return,
-# which could indicate an unknown checksum type, or a missing foosum
-# binary.
-get_checksum() {
-	type="$1"
-	file="$2"
-
-	case "$type" in
-		MD5Sum) md5sum    "$file" | cut -d' ' -f1 ;;
-		SHA1)   sha1sum   "$file" | cut -d' ' -f1 ;;
-		SHA256) sha256sum "$file" | cut -d' ' -f1 ;;
-		*)      error "Unknown checksum type $type for $file"
-	esac
-}
-
 checkmatch() {
-	Release="$1"
-	Packages="$2"
-	pkgfile="$3"
-	pkgsize="$(wc -c < "$Packages" | tr -d ' ')"
+	release="$1"
+	packages="$2"
+	pkgmd5="$3"
+	pkgsize="$4"
 
-	# Note: When checksum types are modified by the FTP team, make
-	# sure to update both the list below and the case statement in
-	# get_checksum().
-	for checksumtype in MD5Sum SHA1 SHA256; do
-		pkgchecksum=$(get_checksum "$checksumtype" "$Packages")
-		if [ -z "$pkgchecksum" ]; then
-			error "Please report a bug: get_checksum() returned nothing"
-		fi
-
-		set -e
-		sed -n "/^$checksumtype:\$/ b LOOP; b; : PRINT; /:\$/q; p; : LOOP; n; b PRINT" \
-		       "$Release" | (
-			found=0
-			while read checksum size file; do
-				if [ "$file" = "$pkgfile" ]; then
-					if [ "$checksum" != "$pkgchecksum" ]; then
-						error "$checksumtype mismatch for $pkgfile ($checksum != $pkgchecksum)."
-					fi
-					if [ "$size" != "$pkgsize" ]; then
-						error "Size mismatch for $pkgfile ($size != $pkgsize)."
-					fi
-					found=1
+	set -e
+	sed -n '/^MD5Sum:$/ b LOOP; b; : PRINT; /:$/q; p; : LOOP; n; b PRINT' \
+	       "$release" | (
+		while read md5 size file; do
+			if [ "$file" = "$packages" ]; then
+				if [ "$md5" != "$pkgmd5" ]; then
+					error "MD5 mismatch for $packages ($md5 != $pkgmd5)."
 				fi
-			done
-			if [ "$found" != 1 ]; then
-				error "$pkgfile not found in $Release (for $checksumtype checksum)."
+				if [ "$size" != "$pkgsize" ]; then
+					error "Size mismatch for $packages ($size != $pkgsize)."
+				fi
+				return 0
 			fi
-		)
-		set +e
-	done
+		done
+		error "$packages not found in $release."
+	)
+	set +e
 }
 
 read_gpg_status() {
@@ -138,7 +110,7 @@ case "$cmd" in
 		error "No components listed in $Release."
 	fi
 	for comp in $components; do
-		for ext in '.xz' '.gz' ''; do
+		for ext in '.gz' ''; do
 			pkgfile="$comp/debian-installer/binary-$ARCH/Packages$ext"
 			line=`grep $pkgfile\$ $Release 2>/dev/null`
 			if [ $? != 0 ]; then
@@ -147,13 +119,13 @@ case "$cmd" in
 			Packages="/tmp/net-retriever-$$-Packages"
 			rm -f "$Packages"
 			fetch "dists/$codename/$pkgfile" "$Packages" || continue
-			checkmatch "$Release" "$Packages" "$pkgfile"
+			checkmatch "$Release" "$pkgfile" \
+				"$(md5sum "$Packages" | cut -d' ' -f1)" \
+				"$(wc -c < "$Packages" | tr -d ' ')"
 			if [ "$ext" = '' ]; then
 				cat "$Packages" >> "$1"
 			elif [ "$ext" = .gz ]; then
 				zcat "$Packages" >> "$1"
-			elif [ "$ext" = .xz ]; then
-				xzcat "$Packages" >> "$1"
 			fi
 			ret=0
 			break
diff --git a/usb/initrd/wheezy-netboot/usr/lib/post-base-installer.d/50install-firmware b/usb/initrd/wheezy-netboot/usr/lib/post-base-installer.d/50install-firmware
--- a/usb/initrd/wheezy-netboot/usr/lib/post-base-installer.d/50install-firmware
+++ b/usb/initrd/wheezy-netboot/usr/lib/post-base-installer.d/50install-firmware
@@ -12,11 +12,21 @@ if [ -d /lib/firmware ]; then
 	done
 fi
 
-# enable non-free repository if any firmware / injected drivers are
-# detected.
+deb_package () {
+	ar p "$1" control.tar.gz | tar zxO ./control | grep 'Package:' |  sed -e 's/Package: *//'
+}
+
+# install cached firmware debs
 if [ -d /var/cache/firmware ]; then
 	for deb in /var/cache/firmware/*.deb; do
 		if [ -f "$deb" ]; then
+			cp -a "$deb" /target/tmp
+			# TODO debconf passthrough
+			if ! in-target dpkg -i "/tmp/$(basename "$deb")"; then
+				# dpkg failed, force removal of package
+				in-target dpkg --force-depends --remove "$(deb_package "$deb")" || true
+			fi
+			rm -f "/target/tmp/$deb"
 			need_nonfree=1
 		fi
 	done
